services:
  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
    networks:
      - backend

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    volumes:
      - ./frontend:/frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_URL=http://app:8000
    depends_on:
      - app
    networks:
      - frontend

networks:
  backend:
  frontend:
