# Generated by Django 5.1.5 on 2025-01-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
